version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    groups:
      npm-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
