import {
    LogOut,
    Trash2,
    AlertTriangle,
    CheckCircle,
    XCircle,
    Info,
    AlertCircle,
    ShieldAlert,
    UserX,
    Power,
    RefreshCw,
    Save,
    Send,
    Download,
    Upload,
    Edit,
    Plus,
    Minus,
    X,
    Check,
    ChevronRight,
    ChevronLeft,
    ChevronDown,
    ChevronUp,
    MoreHorizontal,
    MoreVertical,
    Settings,
    User,
    Users,
    Building2,
    Shield,
    Lock,
    Unlock,
    Eye,
    EyeOff,
    Mail,
    Key,
    Search,
    Filter,
    Calendar,
    Clock,
    Bell,
    BellOff,
    Star,
    Heart,
    Bookmark,
    Share2,
    Copy,
    Clipboard,
    Link,
    ExternalLink,
    Home,
    LayoutDashboard,
    BarChart3,
    PieChart,
    TrendingUp,
    TrendingDown,
    Activity,
    FileText,
    Folder,
    FolderOpen,
    Image,
    Video,
    Music,
    File,
    Archive,
    Database,
    Server,
    Cloud,
    Wifi,
    WifiOff,
    Globe,
    Map,
    MapPin,
    Phone,
    MessageSquare,
    MessageCircle,
    HelpCircle,
    Zap,
    Sun,
    Moon,
    Loader2,
} from 'lucide-react';

export const Icons = {
    logout: LogOut,
    delete: Trash2,
    warning: AlertTriangle,
    success: CheckCircle,
    error: XCircle,
    info: Info,
    alert: AlertCircle,
    security: ShieldAlert,
    userRemove: UserX,
    power: Power,
    refresh: RefreshCw,
    save: Save,
    send: Send,
    download: Download,
    upload: Upload,
    edit: Edit,
    add: Plus,
    remove: Minus,
    close: X,
    check: Check,
    chevronRight: ChevronRight,
    chevronLeft: ChevronLeft,
    chevronDown: ChevronDown,
    chevronUp: ChevronUp,
    moreHorizontal: MoreHorizontal,
    moreVertical: MoreVertical,
    settings: Settings,
    user: User,
    users: Users,
    organization: Building2,
    shield: Shield,
    lock: Lock,
    unlock: Unlock,
    eye: Eye,
    eyeOff: EyeOff,
    mail: Mail,
    key: Key,
    search: Search,
    filter: Filter,
    calendar: Calendar,
    clock: Clock,
    bell: Bell,
    bellOff: BellOff,
    star: Star,
    heart: Heart,
    bookmark: Bookmark,
    share: Share2,
    copy: Copy,
    clipboard: Clipboard,
    link: Link,
    externalLink: ExternalLink,
    home: Home,
    dashboard: LayoutDashboard,
    chart: BarChart3,
    pieChart: PieChart,
    trendUp: TrendingUp,
    trendDown: TrendingDown,
    activity: Activity,
    file: FileText,
    folder: Folder,
    folderOpen: FolderOpen,
    image: Image,
    video: Video,
    music: Music,
    document: File,
    archive: Archive,
    database: Database,
    server: Server,
    cloud: Cloud,
    wifi: Wifi,
    wifiOff: WifiOff,
    globe: Globe,
    map: Map,
    mapPin: MapPin,
    phone: Phone,
    message: MessageSquare,
    chat: MessageCircle,
    help: HelpCircle,
    zap: Zap,
    sun: Sun,
    moon: Moon,
    loader: Loader2,
};

export const ModalIcons = {
    delete: { icon: Trash2, color: 'var(--ds-error-base)' },
    logout: { icon: LogOut, color: 'var(--ds-error-base)' },
    warning: { icon: AlertTriangle, color: 'var(--ds-warning-base)' },
    success: { icon: CheckCircle, color: 'var(--ds-success-base)' },
    error: { icon: XCircle, color: 'var(--ds-error-base)' },
    info: { icon: Info, color: 'var(--ds-info-base)' },
    confirm: { icon: CheckCircle, color: 'var(--ds-brand-500)' },
    security: { icon: ShieldAlert, color: 'var(--ds-warning-base)' },
    power: { icon: Power, color: 'var(--ds-error-base)' },
};

export default Icons;
