export const COUNTRIES_WITH_REGIONS = [
    {
        value: 'tanzania',
        label: 'Tanzania',
        regions: [
            { value: 'dar_es_salaam', label: 'Dar es Salaam' },
            { value: 'arusha', label: 'Arusha' },
            { value: 'mwanza', label: 'Mwanza' },
            { value: 'dodoma', label: 'Dodoma' },
            { value: 'tanga', label: 'Tanga' },
            { value: 'morogoro', label: 'Morogoro' },
            { value: 'mbeya', label: 'Mbeya' },
            { value: 'zanzibar', label: 'Zanzibar' },
        ]
    },
    {
        value: 'kenya',
        label: 'Kenya',
        regions: [
            { value: 'nairobi', label: 'Nairobi' },
            { value: 'mombasa', label: 'Mombasa' },
            { value: 'kisumu', label: 'Kisumu' },
            { value: 'nakuru', label: 'Nakuru' },
            { value: 'eldoret', label: 'Eldoret' },
        ]
    },
    {
        value: 'uganda',
        label: 'Uganda',
        regions: [
            { value: 'kampala', label: 'Kampala' },
            { value: 'entebbe', label: 'Entebbe' },
            { value: 'jinja', label: 'Jinja' },
            { value: 'mbarara', label: 'Mbarara' },
            { value: 'gulu', label: 'Gulu' },
        ]
    },
    {
        value: 'rwanda',
        label: 'Rwanda',
        regions: [
            { value: 'kigali', label: 'Kigali' },
            { value: 'butare', label: 'Butare' },
            { value: 'gisenyi', label: 'Gisenyi' },
            { value: 'ruhengeri', label: 'Ruhengeri' },
        ]
    },
    {
        value: 'ethiopia',
        label: 'Ethiopia',
        regions: [
            { value: 'addis_ababa', label: 'Addis Ababa' },
            { value: 'dire_dawa', label: 'Dire Dawa' },
            { value: 'mekelle', label: 'Mekelle' },
            { value: 'gondar', label: 'Gondar' },
            { value: 'hawassa', label: 'Hawassa' },
        ]
    },
];

export const DONORS = [
    { id: 'd1', name: 'World Health Organization', logo: null, code: 'WHO' },
    { id: 'd2', name: 'UNICEF', logo: null, code: 'UNICEF' },
    { id: 'd3', name: 'Bill & Melinda Gates Foundation', logo: null, code: 'BMGF' },
    { id: 'd4', name: 'USAID', logo: null, code: 'USAID' },
    { id: 'd5', name: 'World Bank', logo: null, code: 'WB' },
    { id: 'd6', name: 'African Development Bank', logo: null, code: 'AFDB' },
    { id: 'd7', name: 'European Union', logo: null, code: 'EU' },
    { id: 'd8', name: 'DFID', logo: null, code: 'DFID' },
];

export const MANAGERS = [
    { id: 'm1', first_name: 'John', last_name: 'Kariuki', email: 'john.kariuki@datastride.com', profile_image: 'https://randomuser.me/api/portraits/men/1.jpg', submissions_count: 156 },
    { id: 'm2', first_name: 'Sarah', last_name: 'Mwangi', email: 'sarah.mwangi@datastride.com', profile_image: 'https://randomuser.me/api/portraits/women/2.jpg', submissions_count: 234 },
    { id: 'm3', first_name: 'David', last_name: 'Ochieng', email: 'david.ochieng@datastride.com', profile_image: 'https://randomuser.me/api/portraits/men/3.jpg', submissions_count: 189 },
    { id: 'm4', first_name: 'Grace', last_name: 'Wanjiku', email: 'grace.wanjiku@datastride.com', profile_image: 'https://randomuser.me/api/portraits/women/4.jpg', submissions_count: 278 },
    { id: 'm5', first_name: 'Peter', last_name: 'Kimani', email: 'peter.kimani@datastride.com', profile_image: 'https://randomuser.me/api/portraits/men/5.jpg', submissions_count: 145 },
    { id: 'm6', first_name: 'Mary', last_name: 'Achieng', email: 'mary.achieng@datastride.com', profile_image: 'https://randomuser.me/api/portraits/women/6.jpg', submissions_count: 312 },
];

export const FIELD_OFFICERS = [
    { id: 'fo1', first_name: 'James', last_name: 'Mutua', email: 'james.mutua@datastride.com', profile_image: 'https://randomuser.me/api/portraits/men/11.jpg', submissions_count: 89 },
    { id: 'fo2', first_name: 'Lucy', last_name: 'Wambui', email: 'lucy.wambui@datastride.com', profile_image: 'https://randomuser.me/api/portraits/women/12.jpg', submissions_count: 112 },
    { id: 'fo3', first_name: 'Michael', last_name: 'Otieno', email: 'michael.otieno@datastride.com', profile_image: 'https://randomuser.me/api/portraits/men/13.jpg', submissions_count: 76 },
    { id: 'fo4', first_name: 'Jane', last_name: 'Njeri', email: 'jane.njeri@datastride.com', profile_image: 'https://randomuser.me/api/portraits/women/14.jpg', submissions_count: 98 },
];

export const THEMATIC_AREAS = [
    { value: 'health', label: 'Health & Nutrition' },
    { value: 'education', label: 'Education' },
    { value: 'agriculture', label: 'Agriculture & Food Security' },
    { value: 'wash', label: 'WASH (Water, Sanitation & Hygiene)' },
    { value: 'livelihood', label: 'Livelihood & Economic Development' },
    { value: 'environment', label: 'Environment & Climate' },
    { value: 'governance', label: 'Governance & Policy' },
    { value: 'protection', label: 'Protection & Human Rights' },
    { value: 'slums_living', label: "Slum's Living" },
];

export const LANGUAGES = [
    { value: 'english', label: 'English' },
    { value: 'swahili', label: 'Swahili' },
    { value: 'french', label: 'French' },
    { value: 'arabic', label: 'Arabic' },
    { value: 'amharic', label: 'Amharic' },
];

export const SYNC_METHODS = [
    { value: 'auto', label: 'Automatic' },
    { value: 'manual', label: 'Manual' },
    { value: 'scheduled', label: 'Scheduled' },
];

export const PROJECT_STATUSES = [
    { value: 'draft', label: 'Draft', color: '#64748b' },
    { value: 'active', label: 'Active', color: '#22c55e' },
    { value: 'on_hold', label: 'On Hold', color: '#f59e0b' },
    { value: 'completed', label: 'Completed', color: '#10b981' },
    { value: 'archived', label: 'Archived', color: '#94a3b8' },
];

export const FORM_STATUSES = [
    { value: 'draft', label: 'Draft', color: '#64748b' },
    { value: 'published', label: 'Published', color: '#22c55e' },
    { value: 'closed', label: 'Closed', color: '#ef4444' },
];

export const MOCK_PROJECTS_FULL = [
    {
        id: 'a30617b1-3f6f-4576-83d2-60089017b1e1',
        project_code: 'PR-USL531',
        name: 'Urban Slum Living Conditions Assessment',
        description: 'A comprehensive survey capturing sanitation, housing quality, water access, waste disposal systems, and health risks in informal settlements.',
        is_active: true,
        start_date: '2025-11-13',
        end_date: '2026-01-31',
        status: 'active',
        country: 'Tanzania',
        regions: ['Tanga', 'Dar es Salaam'],
        thematic_area: 'slums_living',
        language: 'english',
        sync_method: 'manual',
        sla_enabled: true,
        sla_days: 7,
        offline_enabled: true,
        logo: null,
        banner: null,
        created_by: '593e80e3-e6b3-4bfc-9b60-eede370dab36',
        created_at: '2025-11-18T09:59:15.000000Z',
        updated_at: '2026-01-10T12:43:20.000000Z',
        forms_count: 6,
        submissions_count: 1248,
        members_count: 12,
        documents_count: 8,
        gradient: 'linear-gradient(135deg, #10b981, #059669)',
        forms: [
            { id: 'f1', form_code: 'FR-ECP2152', name: 'Elder Citizen Poll', description: null, status: 'published', is_active: true, is_duplicate: false, is_master: false, submissions_count: 342, fields_count: 24, created_at: '2025-11-26T07:35:33.000000Z', image: 'https://images.unsplash.com/photo-1581579438747-1dc8d17bbce4?w=400', form_assignees: [{ id: 'm1', first_name: 'John', last_name: 'Kariuki', profile_image: 'https://randomuser.me/api/portraits/men/1.jpg', full_name: 'John Kariuki' }] },
            { id: 'f2', form_code: 'FR-HHS4521', name: 'Household Survey', description: 'Comprehensive household data collection', status: 'published', is_active: true, is_duplicate: false, is_master: true, submissions_count: 287, fields_count: 45, created_at: '2025-11-20T10:15:00.000000Z', image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=400', form_assignees: [{ id: 'm2', first_name: 'Sarah', last_name: 'Mwangi', profile_image: 'https://randomuser.me/api/portraits/women/2.jpg', full_name: 'Sarah Mwangi' }] },
            { id: 'f3', form_code: 'FR-WAS8871', name: 'Water Access Survey', description: 'Water source and quality assessment', status: 'published', is_active: true, is_duplicate: false, is_master: false, submissions_count: 198, fields_count: 18, created_at: '2025-11-22T14:30:00.000000Z', image: 'https://images.unsplash.com/photo-1538300342682-cf57afb97285?w=400', form_assignees: [{ id: 'm1', first_name: 'John', last_name: 'Kariuki', profile_image: 'https://randomuser.me/api/portraits/men/1.jpg', full_name: 'John Kariuki' }] },
            { id: 'f4', form_code: 'FR-SAN3345', name: 'Sanitation Assessment', description: 'Toilet facilities and waste management', status: 'published', is_active: true, is_duplicate: false, is_master: false, submissions_count: 256, fields_count: 22, created_at: '2025-11-24T09:00:00.000000Z', image: 'https://images.unsplash.com/photo-1584432810601-6c7f27d2362b?w=400', form_assignees: [{ id: 'm3', first_name: 'David', last_name: 'Ochieng', profile_image: 'https://randomuser.me/api/portraits/men/3.jpg', full_name: 'David Ochieng' }] },
            { id: 'f5', form_code: 'FR-HLT9912', name: 'Health Risk Assessment', description: 'Disease prevalence and health access', status: 'draft', is_active: true, is_duplicate: false, is_master: false, submissions_count: 0, fields_count: 35, created_at: '2025-12-01T11:20:00.000000Z', image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=400', form_assignees: [] },
            { id: 'f6', form_code: 'FR-FBK7721', name: 'Feedback Form', description: 'Community feedback collection', status: 'published', is_active: true, is_duplicate: true, is_master: false, submissions_count: 165, fields_count: 12, created_at: '2025-12-05T16:45:00.000000Z', image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400', form_assignees: [{ id: 'm4', first_name: 'Grace', last_name: 'Wanjiku', profile_image: 'https://randomuser.me/api/portraits/women/4.jpg', full_name: 'Grace Wanjiku' }] },
        ],
        managers: [
            { id: 'm1', first_name: 'John', last_name: 'Kariuki', profile_image: 'https://randomuser.me/api/portraits/men/1.jpg', full_name: 'John Kariuki', submissions_count: 156, role: 'Project Manager' },
            { id: 'm2', first_name: 'Sarah', last_name: 'Mwangi', profile_image: 'https://randomuser.me/api/portraits/women/2.jpg', full_name: 'Sarah Mwangi', submissions_count: 234, role: 'Field Coordinator' },
        ],
        donors: [
            { id: 'd1', name: 'World Health Organization', code: 'WHO' },
            { id: 'd3', name: 'Bill & Melinda Gates Foundation', code: 'BMGF' },
        ],
        team_members: [
            { id: 'm1', full_name: 'John Kariuki', role: 'Project Manager', submissions_count: 156 },
            { id: 'm2', full_name: 'Sarah Mwangi', role: 'Field Coordinator', submissions_count: 234 },
            { id: 'fo1', full_name: 'James Mutua', role: 'Field Officer', submissions_count: 89 },
            { id: 'fo2', full_name: 'Lucy Wambui', role: 'Field Officer', submissions_count: 112 },
        ],
        recent_activity: [
            { id: 'a1', message: 'New submission received for Household Survey', created_at: '2026-01-12T08:30:00.000000Z', type: 'submission' },
            { id: 'a2', message: 'John Kariuki completed 5 submissions', created_at: '2026-01-11T16:45:00.000000Z', type: 'milestone' },
            { id: 'a3', message: 'Health Risk Assessment form updated', created_at: '2026-01-11T14:20:00.000000Z', type: 'form_update' },
            { id: 'a4', message: 'New team member Lucy Wambui added', created_at: '2026-01-10T10:00:00.000000Z', type: 'team' },
            { id: 'a5', message: 'Water Access Survey published', created_at: '2026-01-09T09:15:00.000000Z', type: 'form_publish' },
        ],
        timeline: [
            { id: 't1', title: 'Project Created', description: 'Project initialized with basic settings', date: '2025-11-18', status: 'completed', type: 'milestone' },
            { id: 't2', title: 'Forms Designed', description: '6 forms created and configured', date: '2025-11-26', status: 'completed', type: 'task' },
            { id: 't3', title: 'Team Onboarded', description: '12 team members assigned', date: '2025-12-01', status: 'completed', type: 'milestone' },
            { id: 't4', title: 'Data Collection Started', description: 'Field data collection commenced', date: '2025-12-05', status: 'completed', type: 'milestone' },
            { id: 't5', title: '50% Target Reached', description: '624 submissions collected', date: '2026-01-05', status: 'completed', type: 'milestone' },
            { id: 't6', title: 'Mid-term Review', description: 'Scheduled quality assessment', date: '2026-01-15', status: 'pending', type: 'task' },
            { id: 't7', title: 'Data Collection Complete', description: 'Target: 1500 submissions', date: '2026-01-31', status: 'pending', type: 'milestone' },
        ],
        documents: [
            { id: 'doc1', name: 'Project Proposal.pdf', type: 'pdf', size: '2.4 MB', uploaded_at: '2025-11-15T10:00:00.000000Z' },
            { id: 'doc2', name: 'Field Manual.pdf', type: 'pdf', size: '1.8 MB', uploaded_at: '2025-11-20T14:30:00.000000Z' },
            { id: 'doc3', name: 'Training Materials.pptx', type: 'pptx', size: '5.2 MB', uploaded_at: '2025-11-22T09:15:00.000000Z' },
            { id: 'doc4', name: 'Budget Report Q4.xlsx', type: 'xlsx', size: '456 KB', uploaded_at: '2025-12-01T11:00:00.000000Z' },
            { id: 'doc5', name: 'Consent Form Template.docx', type: 'docx', size: '124 KB', uploaded_at: '2025-11-18T16:45:00.000000Z' },
            { id: 'doc6', name: 'Progress Report Dec.pdf', type: 'pdf', size: '890 KB', uploaded_at: '2026-01-02T10:30:00.000000Z' },
        ],
    },
    {
        id: 'b41728c2-4g7h-5687-94e3-71190128c2f2',
        project_code: 'PR-AGC2026',
        name: 'Agricultural Census 2026',
        description: 'National agricultural data collection initiative covering crop production, livestock, and farm economics.',
        is_active: true,
        start_date: '2025-10-01',
        end_date: '2026-03-31',
        status: 'active',
        country: 'Kenya',
        regions: ['Nairobi', 'Nakuru', 'Kisumu'],
        thematic_area: 'agriculture',
        language: 'english',
        sync_method: 'auto',
        sla_enabled: true,
        sla_days: 5,
        offline_enabled: true,
        logo: null,
        banner: null,
        forms_count: 4,
        submissions_count: 892,
        members_count: 8,
        documents_count: 5,
        gradient: 'linear-gradient(135deg, #10b981, #059669)',
        created_at: '2025-10-01T08:00:00.000000Z',
        updated_at: '2026-01-08T14:20:00.000000Z',
        forms: [
            { id: 'f7', form_code: 'FR-FRM445', name: 'Farm Registration', status: 'published', submissions_count: 445, fields_count: 28, image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400' },
            { id: 'f8', form_code: 'FR-CRP234', name: 'Crop Assessment', status: 'published', submissions_count: 234, fields_count: 32, image: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=400' },
            { id: 'f9', form_code: 'FR-LST123', name: 'Livestock Count', status: 'published', submissions_count: 123, fields_count: 20, image: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=400' },
            { id: 'f10', form_code: 'FR-WTR090', name: 'Water Resources', status: 'published', submissions_count: 90, fields_count: 15, image: 'https://images.unsplash.com/photo-1470770903676-69b98201ea1c?w=400' },
        ],
        managers: [{ id: 'm3', first_name: 'David', last_name: 'Ochieng', full_name: 'David Ochieng', profile_image: 'https://randomuser.me/api/portraits/men/3.jpg' }],
        donors: [{ id: 'd4', name: 'USAID', code: 'USAID' }],
        team_members: [],
        recent_activity: [],
        timeline: [],
        documents: [],
    },
    {
        id: 'c52839d3-5h8i-6798-05f4-82201239d3g3',
        project_code: 'PR-EDU2026',
        name: 'Education Quality Assessment',
        description: 'School performance and student outcome tracking across primary and secondary schools.',
        is_active: false,
        start_date: '2025-08-15',
        end_date: '2025-12-31',
        status: 'on_hold',
        country: 'Uganda',
        regions: ['Kampala', 'Jinja'],
        thematic_area: 'education',
        language: 'english',
        sync_method: 'manual',
        sla_enabled: false,
        sla_days: 0,
        offline_enabled: true,
        logo: null,
        banner: null,
        forms_count: 3,
        submissions_count: 567,
        members_count: 6,
        documents_count: 4,
        gradient: 'linear-gradient(135deg, #f59e0b, #d97706)',
        created_at: '2025-08-15T10:00:00.000000Z',
        updated_at: '2025-12-20T09:30:00.000000Z',
        forms: [],
        managers: [],
        donors: [],
        team_members: [],
        recent_activity: [],
        timeline: [],
        documents: [],
    },
    {
        id: 'd63940e4-6i9j-7809-16g5-93312340e4h4',
        project_code: 'PR-INF2026',
        name: 'Infrastructure Development Audit',
        description: 'Comprehensive assessment of public infrastructure including roads, bridges, and public buildings.',
        is_active: true,
        start_date: '2025-06-01',
        end_date: '2025-11-30',
        status: 'completed',
        country: 'Rwanda',
        regions: ['Kigali', 'Butare'],
        thematic_area: 'governance',
        language: 'english',
        sync_method: 'auto',
        sla_enabled: true,
        sla_days: 3,
        offline_enabled: false,
        logo: null,
        banner: null,
        forms_count: 6,
        submissions_count: 2341,
        members_count: 15,
        documents_count: 12,
        gradient: 'linear-gradient(135deg, #10b981, #059669)',
        created_at: '2025-06-01T08:00:00.000000Z',
        updated_at: '2025-11-30T17:00:00.000000Z',
        forms: [],
        managers: [],
        donors: [],
        team_members: [],
        recent_activity: [],
        timeline: [],
        documents: [],
    },
    {
        id: 'e74051f5-7j0k-8910-27h6-04423451f5i5',
        project_code: 'PR-WQS2026',
        name: 'Water Quality Monitoring Survey',
        description: 'Regional water quality monitoring and assessment program for drinking water sources.',
        is_active: true,
        start_date: '2025-12-01',
        end_date: '2026-05-31',
        status: 'active',
        country: 'Ethiopia',
        regions: ['Addis Ababa', 'Hawassa'],
        thematic_area: 'wash',
        language: 'amharic',
        sync_method: 'scheduled',
        sla_enabled: true,
        sla_days: 7,
        offline_enabled: true,
        logo: null,
        banner: null,
        forms_count: 2,
        submissions_count: 423,
        members_count: 5,
        documents_count: 3,
        gradient: 'linear-gradient(135deg, #0ea5e9, #0284c7)',
        created_at: '2025-12-01T10:00:00.000000Z',
        updated_at: '2026-01-10T15:30:00.000000Z',
        forms: [],
        managers: [],
        donors: [],
        team_members: [],
        recent_activity: [],
        timeline: [],
        documents: [],
    },
    {
        id: 'f85162g6-8k1l-9021-38i7-15534562g6j6',
        project_code: 'PR-POP2026',
        name: 'Population Census 2026',
        description: 'National demographic data collection covering population, housing, and socioeconomic indicators.',
        is_active: false,
        start_date: '2026-03-01',
        end_date: '2026-09-30',
        status: 'draft',
        country: 'Tanzania',
        regions: [],
        thematic_area: 'governance',
        language: 'swahili',
        sync_method: 'manual',
        sla_enabled: false,
        sla_days: 0,
        offline_enabled: true,
        logo: null,
        banner: null,
        forms_count: 0,
        submissions_count: 0,
        members_count: 3,
        documents_count: 1,
        gradient: 'linear-gradient(135deg, #ec4899, #be185d)',
        created_at: '2026-01-05T14:00:00.000000Z',
        updated_at: '2026-01-05T14:00:00.000000Z',
        forms: [],
        managers: [],
        donors: [],
        team_members: [],
        recent_activity: [],
        timeline: [],
        documents: [],
    },
];

export const MOCK_SUBMISSIONS = [
    {
        id: 's1',
        submission_code: 'SUB-001234',
        form_id: 'f1',
        form_name: 'Elder Citizen Poll',
        form_code: 'FR-ECP2152',
        project_id: 'a30617b1-3f6f-4576-83d2-60089017b1e1',
        project_name: 'Urban Slum Living Conditions Assessment',
        submitted_by: { id: 'fo1', full_name: 'James Mutua', profile_image: 'https://randomuser.me/api/portraits/men/11.jpg' },
        submitted_at: '2026-01-12T08:30:00.000000Z',
        status: 'approved',
        location: { lat: -6.7924, lng: 39.2083, text: 'Dar es Salaam, Kinondoni District' },
        data: {
            respondent_name: 'Amina Hassan',
            age: 67,
            gender: 'female',
            health_status: 'fair',
            house_photo: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=400',
            signature: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Signature_sample.svg/1200px-Signature_sample.svg.png',
            interview_location: '-6.7924, 39.2083'
        },
    },
    {
        id: 's2',
        submission_code: 'SUB-001235',
        form_id: 'f2',
        form_name: 'Household Survey',
        form_code: 'FR-HHS4521',
        project_id: 'a30617b1-3f6f-4576-83d2-60089017b1e1',
        project_name: 'Urban Slum Living Conditions Assessment',
        submitted_by: { id: 'fo2', full_name: 'Lucy Wambui', profile_image: 'https://randomuser.me/api/portraits/women/12.jpg' },
        submitted_at: '2026-01-12T09:15:00.000000Z',
        status: 'pending',
        location: { lat: -6.8001, lng: 39.2150, text: 'Dar es Salaam, Ilala District' },
        data: { household_head: 'John Mwamba', members: 6, income_level: 'low' },
    },
    {
        id: 's3',
        submission_code: 'SUB-001236',
        form_id: 'f3',
        form_name: 'Water Access Survey',
        form_code: 'FR-WAS8871',
        project_id: 'a30617b1-3f6f-4576-83d2-60089017b1e1',
        project_name: 'Urban Slum Living Conditions Assessment',
        submitted_by: { id: 'fo1', full_name: 'James Mutua', profile_image: 'https://randomuser.me/api/portraits/men/11.jpg' },
        submitted_at: '2026-01-11T16:45:00.000000Z',
        status: 'approved',
        location: { lat: -6.7856, lng: 39.2234, text: 'Dar es Salaam, Temeke District' },
        data: { water_source: 'public_tap', distance: '500m', quality: 'acceptable' },
    },
    {
        id: 's4',
        submission_code: 'SUB-001237',
        form_id: 'f1',
        form_name: 'Elder Citizen Poll',
        form_code: 'FR-ECP2152',
        project_id: 'a30617b1-3f6f-4576-83d2-60089017b1e1',
        project_name: 'Urban Slum Living Conditions Assessment',
        submitted_by: { id: 'fo3', full_name: 'Michael Otieno', profile_image: 'https://randomuser.me/api/portraits/men/13.jpg' },
        submitted_at: '2026-01-11T14:20:00.000000Z',
        status: 'rejected',
        location: { lat: -6.8123, lng: 39.2089, text: 'Dar es Salaam, Ubungo District' },
        data: { respondent_name: 'Peter Kimweri', age: 72, gender: 'male', health_status: 'poor' },
    },
    {
        id: 's5',
        submission_code: 'SUB-001238',
        form_id: 'f4',
        form_name: 'Sanitation Assessment',
        form_code: 'FR-SAN3345',
        project_id: 'a30617b1-3f6f-4576-83d2-60089017b1e1',
        project_name: 'Urban Slum Living Conditions Assessment',
        submitted_by: { id: 'fo4', full_name: 'Jane Njeri', profile_image: 'https://randomuser.me/api/portraits/women/14.jpg' },
        submitted_at: '2026-01-11T10:00:00.000000Z',
        status: 'approved',
        location: { lat: -6.7789, lng: 39.1956, text: 'Dar es Salaam, Kigamboni District' },
        data: { toilet_type: 'pit_latrine', condition: 'fair', shared: true },
    },
    {
        id: 's6',
        submission_code: 'SUB-009999',
        form_id: 'f5',
        form_name: 'Multi-Media Audit Master',
        form_code: 'FR-ELITE-99',
        project_id: 'a30617b1-3f6f-4576-83d2-60089017b1e1',
        project_name: 'Urban Slum Living Conditions Assessment',
        submitted_by: { id: 'fo1', full_name: 'James Mutua', profile_image: 'https://randomuser.me/api/portraits/men/11.jpg' },
        submitted_at: '2026-01-14T15:20:00.000000Z',
        status: 'pending',
        location: { lat: -1.2921, lng: 36.8219, text: 'Nairobi CBD, Central Region' },
        data: {
            full_name: 'Elite Auditor Pro',
            email_address: 'auditor@datastride.io',
            phone_number: '+254 712 345 678',
            age_count: 32,
            birth_date: '1992-05-24',
            captured_at_time: '15:20:45',
            department_select: 'Field Operations',
            assigned_regions: ['Nairobi', 'Mombasa', 'Kisumu'],
            gps_location: '-1.2921, 36.8219',
            profile_photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800',
            audit_video_file: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4',
            site_voice_note: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
            technical_doc_pdf: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
            authorization_signature: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Signature_sample.svg/1200px-Signature_sample.svg.png',
            additional_notes_desc: 'Initial site assessment complete. All high-fidelity sensors active and synchronizing with the cloud terminal.'
        },
    },
];

export const MOCK_TASKS = [
    {
        id: 'task1',
        title: 'Complete Kinondoni District Survey',
        description: 'Finish all pending household surveys in Kinondoni district by end of week',
        project_id: 'a30617b1-3f6f-4576-83d2-60089017b1e1',
        project_name: 'Urban Slum Living Conditions Assessment',
        assigned_to: { id: 'fo1', full_name: 'James Mutua', profile_image: 'https://randomuser.me/api/portraits/men/11.jpg' },
        assigned_by: { id: 'm1', full_name: 'John Kariuki' },
        deadline: '2026-01-15T17:00:00.000000Z',
        priority: 'high',
        status: 'in_progress',
        target_submissions: 50,
        completed_submissions: 32,
        created_at: '2026-01-08T09:00:00.000000Z',
    },
    {
        id: 'task2',
        title: 'Data Quality Review',
        description: 'Review and validate all submissions from last week',
        project_id: 'a30617b1-3f6f-4576-83d2-60089017b1e1',
        project_name: 'Urban Slum Living Conditions Assessment',
        assigned_to: { id: 'm2', full_name: 'Sarah Mwangi', profile_image: 'https://randomuser.me/api/portraits/women/2.jpg' },
        assigned_by: { id: 'm1', full_name: 'John Kariuki' },
        deadline: '2026-01-14T12:00:00.000000Z',
        priority: 'medium',
        status: 'pending',
        target_submissions: 100,
        completed_submissions: 0,
        created_at: '2026-01-10T11:30:00.000000Z',
    },
    {
        id: 'task3',
        title: 'Training Session - New Form',
        description: 'Conduct training for field officers on the new Health Risk Assessment form',
        project_id: 'a30617b1-3f6f-4576-83d2-60089017b1e1',
        project_name: 'Urban Slum Living Conditions Assessment',
        assigned_to: { id: 'm1', full_name: 'John Kariuki', profile_image: 'https://randomuser.me/api/portraits/men/1.jpg' },
        assigned_by: { id: 'm1', full_name: 'John Kariuki' },
        deadline: '2026-01-20T10:00:00.000000Z',
        priority: 'low',
        status: 'pending',
        target_submissions: null,
        completed_submissions: null,
        created_at: '2026-01-11T15:00:00.000000Z',
    },
    {
        id: 'task4',
        title: 'Ilala District Coverage',
        description: 'Complete water access survey in remaining Ilala areas',
        project_id: 'a30617b1-3f6f-4576-83d2-60089017b1e1',
        project_name: 'Urban Slum Living Conditions Assessment',
        assigned_to: { id: 'fo2', full_name: 'Lucy Wambui', profile_image: 'https://randomuser.me/api/portraits/women/12.jpg' },
        assigned_by: { id: 'm2', full_name: 'Sarah Mwangi' },
        deadline: '2026-01-18T17:00:00.000000Z',
        priority: 'high',
        status: 'in_progress',
        target_submissions: 30,
        completed_submissions: 18,
        created_at: '2026-01-09T14:00:00.000000Z',
    },
];

export const TEMPLATE_FORMS = [
    {
        id: 'tpl1',
        form_code: 'TPL-HHS001',
        name: 'Household Survey Template',
        description: 'Standard household survey template with demographic questions',
        fields_count: 45,
        created_at: '2025-10-15T10:00:00.000000Z',
        source_project: 'Urban Slum Living Conditions Assessment',
        usage_count: 12,
    },
    {
        id: 'tpl2',
        form_code: 'TPL-FBK001',
        name: 'Feedback Form Template',
        description: 'Generic feedback collection template',
        fields_count: 12,
        created_at: '2025-11-20T14:30:00.000000Z',
        source_project: 'Urban Slum Living Conditions Assessment',
        usage_count: 8,
    },
    {
        id: 'tpl3',
        form_code: 'TPL-WAS001',
        name: 'WASH Assessment Template',
        description: 'Water, Sanitation, and Hygiene assessment template',
        fields_count: 28,
        created_at: '2025-09-10T09:00:00.000000Z',
        source_project: 'Water Quality Monitoring Survey',
        usage_count: 15,
    },
];

export const FIELD_TYPES = [
    { type: 'text', label: 'Text', icon: 'Type', category: 'basic' },
    { type: 'number', label: 'Number', icon: 'Hash', category: 'basic' },
    { type: 'email', label: 'Email', icon: 'Mail', category: 'basic' },
    { type: 'phone', label: 'Phone', icon: 'Phone', category: 'basic' },
    { type: 'textarea', label: 'Text Area', icon: 'AlignLeft', category: 'basic' },
    { type: 'date', label: 'Date', icon: 'Calendar', category: 'datetime' },
    { type: 'datetime', label: 'Date & Time', icon: 'CalendarClock', category: 'datetime' },
    { type: 'time', label: 'Time', icon: 'Clock', category: 'datetime' },
    { type: 'select', label: 'Dropdown', icon: 'ChevronDown', category: 'choice' },
    { type: 'multi_select', label: 'Multi Select', icon: 'ListChecks', category: 'choice' },
    { type: 'radio', label: 'Radio Buttons', icon: 'Circle', category: 'choice' },
    { type: 'checkbox', label: 'Checkboxes', icon: 'CheckSquare', category: 'choice' },
    { type: 'file', label: 'File Upload', icon: 'Upload', category: 'media' },
    { type: 'multi_file', label: 'Multi File', icon: 'Files', category: 'media' },
    { type: 'image', label: 'Image', icon: 'Image', category: 'media' },
    { type: 'audio', label: 'Audio', icon: 'Mic', category: 'media' },
    { type: 'video', label: 'Video', icon: 'Video', category: 'media' },
    { type: 'gps', label: 'GPS Location', icon: 'MapPin', category: 'advanced' },
    { type: 'signature', label: 'Signature', icon: 'PenTool', category: 'advanced' },
    { type: 'barcode', label: 'Barcode/QR', icon: 'QrCode', category: 'advanced' },
    { type: 'calculate', label: 'Calculate', icon: 'Calculator', category: 'advanced' },
    { type: 'note', label: 'Note', icon: 'FileText', category: 'layout' },
    { type: 'hidden', label: 'Hidden', icon: 'EyeOff', category: 'advanced' },
];

export const VALIDATION_TYPES = [
    { type: 'required', label: 'Required' },
    { type: 'min_length', label: 'Minimum Length' },
    { type: 'max_length', label: 'Maximum Length' },
    { type: 'min_value', label: 'Minimum Value' },
    { type: 'max_value', label: 'Maximum Value' },
    { type: 'pattern', label: 'Regex Pattern' },
    { type: 'email', label: 'Email Format' },
    { type: 'phone', label: 'Phone Format' },
    { type: 'url', label: 'URL Format' },
];
