name: Auto-Format Code
on:
  push:
    branches: ["**"]
  pull_request:
    types: [opened, synchronize]
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  format:
    name: runner / prettier
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
      - run: npm install
      - name: Prettier Format
        run: npm run format
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto-format code with prettier [skip ci]"
          commit_author_name: Nexo Automator
          commit_author_email: automator@nexo.ai
